install-build-test: &install-build-test
  - checkout
  - restore_cache:
      key: node-modules-{{ checksum "package-lock.json" }}
  - run: npm install
  - save_cache:
      key: node-modules-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  - run: npm run build
  - run: npm test

version: 2.1
jobs:
  test-node-20:
    docker:
      - image: cimg/node:20.19 # Maintenance; EOL 2026.04.30
    steps:
      *install-build-test
  test-node-22:
    docker:
      - image: cimg/node:22.20 # LTS; EOL 2027.04.30
    steps:
      *install-build-test
  test-node-24:
    docker:
      - image: cimg/node:24.9 # Current; EOL 2028.04.30
    steps:
      *install-build-test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - when:
          condition: true
          steps:
            *install-build-test
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

test-filters: &test-filters
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - test-node-20:
          <<: *test-filters
      - test-node-22:
          <<: *test-filters
      - test-node-24:
          <<: *test-filters
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /parser-v[0-9]+(\.[0-9]+)*/
          requires:
            - test-node-20
            - test-node-22
            - test-node-24
